#! /bin/bash

## borra la carpeta input si existe
!hdfs dfs -rm -r -f /tmp/wordcount/input

## crea la carpeta
!hdfs dfs -mkdir /tmp/wordcount/input

## copia los archivos de entrada de la
## maquina local al sistema hdfs
!hdfs dfs -copyFromLocal wordcount/* /tmp/wordcount/input/

## ejecuta la aplicación de spark
spark-submit wordcount.py
